/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/types/runtime-bindings.d.ts --env-interface RuntimeBindings --include-runtime=false` (hash: ed9de43af5d3b6989ef05f4a59ad5632)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../index");
	}
	interface TestEnv {
		ORDER_STATE: KVNamespace;
		DB: D1Database;
		LINE_CHANNEL_TOKEN: SecretsStoreSecret;
		OPENROUTER_API_KEY: SecretsStoreSecret;
		GROQ_API_KEY: SecretsStoreSecret;
		LIFF_ID: "2009555608-DMioljsI";
		LIFF_URL: "https://liff.line.me/2009555608-DMioljsI";
		LINE_RUNTIME_ENABLED: "false";
		LINE_RUNTIME_TENANTS: "[]";
		LINE_RUNTIME_ENVIRONMENT: "staging";
		LINE_SECRET_KEYS: string;
	}
	interface DevEnv {
		ORDER_STATE: KVNamespace;
		DB: D1Database;
		LINE_CHANNEL_TOKEN: SecretsStoreSecret;
		OPENROUTER_API_KEY: SecretsStoreSecret;
		GROQ_API_KEY: SecretsStoreSecret;
		LIFF_ID: "2011224566-kLLdMjkq";
		LIFF_URL: "https://liff.line.me/2011224566-kLLdMjkq";
		LINE_RUNTIME_ENABLED: "false";
		LINE_RUNTIME_TENANTS: "[]";
		LINE_RUNTIME_ENVIRONMENT: "dev";
		LINE_SECRET_KEYS: string;
	}
	interface Env {
		ORDER_STATE: KVNamespace;
		DB: D1Database;
		LINE_CHANNEL_TOKEN: SecretsStoreSecret;
		OPENROUTER_API_KEY: SecretsStoreSecret;
		GROQ_API_KEY: SecretsStoreSecret;
		LIFF_ID: "2009555608-DMioljsI" | "2011224566-kLLdMjkq" | "2009560906-c5taZfiY";
		LIFF_URL: "https://liff.line.me/2009555608-DMioljsI" | "https://liff.line.me/2011224566-kLLdMjkq" | "https://liff.line.me/2009560906-c5taZfiY";
		LINE_RUNTIME_ENABLED: "false";
		LINE_RUNTIME_TENANTS: "[]";
		LINE_RUNTIME_ENVIRONMENT: "staging" | "dev" | "production";
		LINE_SECRET_KEYS: string;
		LINE_TOKEN_BSC?: SecretsStoreSecret;
	}
}
interface RuntimeBindings extends Cloudflare.Env {}
